Just flashing
Berserker66/MultiWorld-Utilities pull request #168
Opened 2021-02-01 03:08 UTC by pepperpow

Accessibility (of the human variety) of removing instance of full screen flashing for players and stream viewers:

Disables the following (and should be tested for any speed inconsistency):

- Aga Lightning Attack
- Aga Cutscene (pre-aga1, introduction demo)
- Vitreous lightning (needs to be checked)
- Weather effects (in standard intro and misery mire)
- Ether (flashing effects)

2021-02-01 14:52 UTC, Berserker66 requested changes

2021-02-01 14:52 UTC, Berserker66 commented on AdjusterMain.py
> +    racerom = rom.read_byte(0x180213) > 0
This line doesn't appear to be used.

2021-02-04 03:05 UTC, pepperpow commented on AdjusterMain.py
> +    racerom = rom.read_byte(0x180213) > 0
Now it is.

2021-02-11 06:10 UTC, pepperpow commented
Oh, latest commit added TWO new features: anti flashing on Dark Mountain and tile reveals on Ether

Separate ASM pull on z3randomizer for a fix on Mountain and Misery Mire for corrupted rain graphics

2021-02-19 16:45 UTC, merged

2021-02-19 16:45 UTC, Berserker66 commented
Thank you!